# GAME PARAMETERS
TOTAL_ROUNDS = 1000000
NUMBER_PLAYERS = 1

TWO   = 2
THREE = 3
FOUR  = 4
FIVE  = 5
SIX   = 6
SEVEN = 7
EIGHT = 8
NINE  = 9
TEN   = 10
JACK  = 11
QUEEN = 12
KING  = 13
ACE   = 14

HEARTS   = 1
DIAMONDS = 2
CLUBS    = 3
SPADES   = 4

STANDARD_CARDS = [ TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT,
                  NINE, TEN, JACK, QUEEN, KING, ACE ]
STANDARD_SUITS = [ HEARTS, CLUBS, DIAMONDS, SPADES ]

BLACKJACK_VALUES = { TWO : 2, THREE : 3, FOUR : 4, FIVE : 5,
                     SIX : 6, SEVEN : 7, EIGHT : 8, NINE : 9,
                     TEN : 10, JACK : 10, QUEEN : 10, KING : 10,
                     ACE : 11 }
HIT = 1
STAND = 2
SPLIT = 3
DOUBLEDOWN = 4

TENS = [TEN, JACK, QUEEN, KING]